### ISSUE TITLE
Version flag does not produce the version number

### ISSUE THREAD

**Issue by KaffeMyers** [RoryQ/wrench#70]
## Expected Behavior
To get the version number when typing in `wrench --version`

## Current Behavior
Output of the command is `(devel)`

## Steps to Reproduce

1. Download latest release
2. Unpack `wrench`
3. run `wrench --version`

## Context (Environment)

* wrench version: 1.11.0

I'm using a script that checks version remotely and locally to see if there is an update available. This can't be done if the version is not produced with the `--version` flag.

**Comment by RoryQ** [comment]
Interesting, looks like the version flag was only being set when `go install`-ed. I'll update the goreleaser config to match.

https://github.com/earthboundkid/versioninfo/blob/v0.22.5/variables.go#L8
